### PR TITLE
Add ExCoveralls code coverage tool

### PR DESCRIPTION
**Pull request by hidnasio**

### CODE REVIEW

**Comment by hidnasio** [comment]
The build is failing because the repo is not in Coveralls yet.

**Comment by san650** [comment]
@hidnasio can you rebase with master?

**Comment by san650** [comment]
I've added the repo to coveralls.io

**Comment by san650** [comment]
https://coveralls.io/github/san650/pretty_print_formatter

**Comment by san650** [comment]
Can you add the badge to the readme?

```
[![Coverage Status](https://coveralls.io/repos/github/san650/pretty_print_formatter/badge.svg?branch=master)](https://coveralls.io/github/san650/pretty_print_formatter?branch=master)
```

**Pull request merged**
